### ISSUE TITLE
Repository peer feedback

### ISSUE THREAD

**Issue by HappyPantss** [InjuMichorius/Filmaholic#1]
### Repository
Hey Inju, bij deze mijn peer review op jouw repository voor de WAFS API opdracht.

Zie de vinkjes (:heavy_check_mark:) en kruisjes (:x:) niet als fout of goed, maar een vinkje is voor als je heta af hebt, en een kruisje voor als er nog iets mist :).

:x: Is there a repo description at the top?
De repo heeft een 'description', maar niet met de goede informatie! Ik zou hier in het kort (MAND) uitleggen wat/ waar voor het project is, en ik zou er een link inzetten naar je live website.

:heavy_check_mark: Is the repo open to issues?
Jazeker! Anders had ik deze issue niet kunnen schrijven! Vergeet dit dus niet bij elke repo te doen die je aanmaakt, het kan erg handig zijn.

:heavy_check_mark: Does it include a gitignore?
Ja! een .gitignore is erg belangrijk. Als je data hebt wat mensen niet mogen lezen, zoals wachtwoorden, zet je dit bestandje in de .gitignore.

:x: Is the concept described well in the readme?
Nope! Nog niet :)

:x: Is the API described in the readme?
Nope! Nog niet :)

Keep coding~~

**Comment by InjuMichorius** [comment]
Hi Sergio 👋
Thanks voor je review! Ik heb al je punten meegenomen in mijn project en verbeterd ✔️
