### ISSUE TITLE
Peer review web-app-from-scratch-2021 week 2

### ISSUE THREAD

**Issue by ofahchouch-gh** [InjuMichorius/Filmaholic#11]
**Over de readme**
- Leuke afbeelding van je website. Ziet er goed uit kwa design.
- Er mist nog informatie in de readme over de API endpoints die je gebruikt.

**Over het actor en interaction diagram**
- Heeft een leuk kleurtje :)
- Is het niet verstandiger om ook entiteiten te gebruiken die te maken hebben met de domein logica? Zoals een class/functies die gerelateerd is/zijn aan de entiteit Movie? 
- Misschien handig om ook de attributen van entiteiten vast te leggen in je actor diagram?
- Verder mis ik ook een entiteit voor de API die je gebruikt, bv ApiHandler, waarin alle API calls staan? Want in het interaction diagram maak je wel gebruik van de TMDB API, maar in het actor diagram zie ik deze entiteit niet?
- De logica in je interaction diagram is echter wel weer heel duidelijk te volgen. Maar ik mis vooral domein logica.

**Over de code**
- Heel goed dat je best practises probeert te volgen :).
- Je hebt een veel mooier interaction diagram, maar dan zie ik maar 1 file waar je in werkt?
- Probeer gelijk al met abstractieniveaus te werken door met modules/classes en het Single Responsibility Principle aan de slag te gaan.
- Pluspunt is dat je css er goed uit ziet.

Verder, probeer je reviews van vorige week te sluiten als dat kan :-)!

**Comment by InjuMichorius** [comment]
Thanks for the review 🔥 I've updated my repository and added your feedback
