### ISSUE TITLE
Feedback week 3

### ISSUE THREAD

**Issue by johancvb** [InjuMichorius/Filmaholic#15]
Yoo!
Ik ga je repo en je code even analyseren en voorzien van feedback.

### Repository

Je repository ziet er duidelijk en clean uit. Je informeert de lezer goed over het concept, en de actor- en interaction diagram zien er strak en logisch uit. Ook vind ik het super vet dat je de best-practices en design patterns vergelijkt met jouw werk.
Wat ik wel mis, is meer uitleg over de API zelf (Welke data wordt er gebruikt? Welke endpoints? etc.), dus probeer dat verder uit te werken. 
Voor de rest ziet je repo/readme er duidelijk en overzichtelijk uit! 

### Code

Helaas rendert je app de data niet uit de API, ik kreeg een 404 error.... Ik denk dat het probleem ligt bij het importeren van de verschillende functies uit andere bestanden. Je hebt nu bijvoorbeeld './api.js', maar volgens mij moet daar nog een mapje tussen, dus './source/api.js'.  ( _maar dit weet ik niet zeker ;)_ ).
Je code ziet er wel heel strak uit. Je gebruikt duidelijke variabelnamen, een overzichtelijk mappenstructuur, en een duidelijke structuur in je code. Hier zou ik niks meer aan veranderen :)

Ondanks dat ik je app niet werkend kan zien, zie ik aan de code dat je lekker bezig bent!
Ik heb er vertrouwen in dat het wel goedkomt. Lekker bezig maat, blijf zo doorgaan!

-- Johan

**Comment by InjuMichorius** [comment]
Thanks for the review 🔥 I've updated my repository and added your feedback
