### ISSUE TITLE
Code peer feedback 1

### ISSUE THREAD

**Issue by HappyPantss** [InjuMichorius/Filmaholic#2]
### Code
Hey Inju, bij deze mijn peer review op jouw code voor de WAFS API opdracht.

Zie de vinkjes (:heavy_check_mark:) en kruisjes (:x:) niet als fout of goed, maar een vinkje is voor als je heta af hebt, en een kruisje voor als er nog iets mist :).

:heavy_check_mark: Try to understand the code flow
1 ding: TOP! Je hebt een duidelijke fetch functie gemaakt, met een mooie loop die door alle resultaten heen gaat, en deze op de pagina zet! Goed dat je een error uitvoerd, wanneer de api niet gecalled kan worden!

:heavy_check_mark: Check the code against our course's best practices
Ik zie geen herhalende code, wat erg goed is, keep this up! En je <script> tag staat mooi voor dat je de </body> afsluit.

:heavy_check_mark: Check the code for consistency, is code being written the same way in different places?
Voor de hoeveelheid code die je nu hebt, zit er zeker consistentie in!

:heavy_check_mark: Does the code follow naming convention? Do variable and function names make sense to you?
De benaming 'html' is wat onduidelijk voor mij, hier kan je bijvoorbeeld 'output' of iets van maken. Vertel hier (niet in al te langen letters) wat hier gebeurd.

Een tip voor je link:
Je kan sommige element van je link (zoals de key) opslaan in een variable, en deze (als het nodig is) later veranderen met code :)

Keep coding~~

**Comment by InjuMichorius** [comment]
Hi Sergio 👋
Thanks voor je review! Ik heb al je punten meegenomen in mijn project en verbeterd ✔️
