### ISSUE TITLE
Feedback: Code (HTML)

### ISSUE THREAD

**Issue by standrd** [InjuMichorius/Filmaholic#4]
## HTML code feedback

* The HTML looks clean and the script is placed at the bottom of the body, which is good. It might need a `defer` tag in it, so the script is executed once the DOM is loaded entirely, but oftentimes it also works without: depends on the JS.

**Comment by InjuMichorius** [comment]
Hi Stan👋
Thanks for your review! I have included all your points in my project and improved ✔️
