### ISSUE TITLE
Feedback: Code (JS)

### ISSUE THREAD

**Issue by standrd** [InjuMichorius/Filmaholic#5]
## Javascript code feedback

* The website is in English, I would also name variables in English: `naam` -> `name`.

* I would remove unnecessary console logs when pushing to Github if the code is functioning well.

* Instead of just throwing an error when the response isnt valid, maybe provide feedback to the frontend HTML:
```
if (!response.ok) {
    throw Error("URL not working")
}
```

**Comment by InjuMichorius** [comment]
Hi Stan 👋
Thanks for the review! I've looked at your points and updated my code ✔️
