### ISSUE TITLE
Feedback: Code consistency

### ISSUE THREAD

**Issue by standrd** [InjuMichorius/Filmaholic#6]
## Code consistency feedback

* Right now there is not much Javascript yet, but later I would recommend to get setup in a better folder structure and start using modules if you're comfortable with them.

* Decide if you put semi-colons at the end where possible, or just don't do it. Right now, there are some places where you did do it, and some where you don't. Try to be consistent.

**Comment by InjuMichorius** [comment]
Hi Stan 👋
Thanks for the review! I've looked at your points and updated my code by adding semi-colons and adding modules✔️
